### PR TITLE
Update readme

### LINKED ISSUE #1: Update the readme
We can update the docs showing what the bot is capable of.

I mean functions available can be moved to the readme file for better documentation.

### PR DESCRIPTION
**Pull request by nirbhay12345**
This PR contains:

 - ADDED README CONTENTS
    - Description
    - Getting started with Telegram bot
    - Telegram API Te=oken
    - Bot Functions

Have tried to use the standard README flows
closes #1

### CODE REVIEW

**Comment by nirbhay12345** [comment]
@thesarthakjain please review this pr and suggest changes of required.

**Review by thesarthakjain — CHANGES_REQUESTED** [review]
That's a very well written readme! I really appreciate the effort!
Can you try to combine the `Getting started with the Telegram-Bot` and `Instructions to run` into a single section? It could go something like:

1. Change working directory.
2. Install requirements.
3. Config.yaml manual setup - This could be a skippable step as step 4 will automatically do the setup for the yaml file.
4. Running the bot.
5. Stopping the bot.

Rest of the content you've added is perfect!

**Comment by nirbhay12345** [comment]
Okay that sure makes sense I'll change the following.

**Comment by nirbhay12345** [comment]
@thesarthakjain I have made the requested changes.

**Pull request merged**
